backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: "public/images/"
public_folder: "/images"
search: false
editor: 
  preview: false
collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: "projects" }
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", minimal: true }
      - { label: "Tags", name: "tags", widget: "list", default: "blog" }
  - name: "existing-pages"
    label: "Existing Pages"
    label_singular: "Existing Page"
    extension: "njk"
    format: "frontmatter"
    files:
        - name: "home"
          label: "Home page"
          extension: "njk"
          format: "frontmatter"
          file: "src/index.njk"
          fields:
              - { label: "Title of page", name: "title", widget: "string" }
              - { label: "Call to action text", name: "jumboText", widget: "markdown", buttons: ["link"], editor_components: [], modes: ["rich_text"] }
              - label: "link"
                name: "link"
                widget: "object"
                fields: 
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
  - label: "Settings"
    name: "settings"
    files: 
      - label: "Header"
        name: "header"
        file: "src/_data/header.json"
        fields: 
          - { label: "Wordmark Title", name: "title", widget: "string" }
          - { label: "Wordmark Subtitle", name: "subtitle", widget: "string" }
          - label: "Links"
            name: "links"
            collapsed: true
            widget: "list"
            fields:
              - {label: Link Text, name: text, widget: string }
              - {label: Link URL, name: url, widget: string }
      - label: "Footer"
        name: "footer"
        file: "src/_data/footer.json"
        fields: 
          - label: "Links"
            name: "links"
            collapsed: true
            widget: "list"
            fields:
              - {label: Link Text, name: text, widget: string }
              - {label: Link URL, name: url, widget: string }
  - label: "Pages"
    name: "pages"
    label_singular: "Page"
    folder: "src/pages"
    slug: "{{slug}}"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - label: "Sections"
        name: "sections"
        label_singular: "section"
        widget: "list"
        types: 
          - label: "Graphic Diptych"
            name: "graphic-diptypch"
            widget: "object"
            fields:
              - { label: "Heading", name: "heading", widget: string }
              - { label: "Paragraph", name: "paragraph", widget: text }
              - { label: "Image", name: "image", widget: image }
              - { label: "Module Type", name: "module", widget: 'hidden', default: "graphic-diptych" }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page-builder.njk' }
      - { label: 'Permalink', name: 'permalink', widget: 'hidden', default: "{{ title | slugify }}/index.html" }